---
- hosts: localhost
  gather_facts: yes

  roles:
      - { role: kurron.time }
      # TODO: figure out how how to have Packer supply the Elasticsearch coordinates
      - { role: kurron.logstash, elastic_elasticsearch_host: search-phoenix-i43nf624oy3q6kba3zomjljrwq.us-west-2.es.amazonaws.com, elastic_elasticsearch_port: 80 }

  post_tasks:
      - name: Test Syslog
        command: "logger --server localhost --port 5514 --priority 0  --tag test 'Hello, World!'"
        become: no

      - name: Install Netcat
        become: yes
        yum:
            name: nc
            state: present
            update_cache: yes
        when: (ansible_distribution == "RedHat")

      - name: Install Netcat
        become: yes
        apt:
            name: nc
            update_cache: no
            state: present
            allow_unauthenticated: no
        when: (ansible_distribution == "Ubuntu")
